// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmekugonmdhhbmmtsjon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZWt1Z29ubWRoaGJtbXRzam9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNzYwMzIsImV4cCI6MjA4MDc1MjAzMn0.B6_xY5lUC0xtujUpqacpn2mKbYuoqzvnYqwJ1R3w7QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
