// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfcfcmtgtgdltnuknqyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmY2ZjbXRndGdkbHRudWtucXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzcwMzIsImV4cCI6MjA2NzYxMzAzMn0.l9V0BVC94R-AE-e9D8kFCl8uEmP9Ov7JA1c218baziE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});